# GitHub Action for Laravel with MySQL and Redis
name: Fusion Play
on: 
  push:
    branches:
    - develop
  pull_request:

jobs:
  fusion-play:
    name: Fusion Play Deployment
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Complile CSS & JavaScript
        run: |
          npm install
          npm run prod
      
      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with: 
          php-version: 8.1
          extensions:  common, cli, mbstring, mysql, curl, fpm, bz2, intl, readline, xml, pcov, xdebug, openssl, PDO, bcmath, fileinfo, json, tokenizer, ctype 