# GitHub Action for Laravel with MySQL and Redis
name: Fusion Play
on: 
  push:
    branches:
    - main
  pull_request:

jobs:
  fusion-play:
    name: Fusion Play Deployment
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Complile CSS & JavaScript
        run: |
          npm install
          npm run prod