# GitHub Action for Laravel with MySQL and Redis
name: Fusion Play
on: 
  push:
    branches:
    - develop
  pull_request:

jobs:
  fusion-play:
    name: Fusion Play Deployment
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Complile CSS & JavaScript
        run: |
          npm install
          npm run prod
      
      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with: 
          php-version: 8.1
          extensions:  mbstring, mysql, curl, bz2, intl, readline, xml, pcov, xdebug, openssl, PDO, bcmath, fileinfo, json, tokenizer, ctype

      - name: Install Composer Dependencies
        run: composer install --no-dev --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Create Deployment Artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${ GITHUB_SHA }".tar.gz --exclude=*.git --exclude=node_modules *

      - name: Store Artifact For Distribution
        uses: action/upload-artifact@v2
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz